# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  difit = {
    pname = "difit";
    version = "v2.2.7";
    src = fetchFromGitHub {
      owner = "yoshiko-pg";
      repo = "difit";
      rev = "v2.2.7";
      fetchSubmodules = false;
      sha256 = "sha256-1YMGvzjHW0XKtMK0uRradFdRAFlCK+EeR768GYeTunY=";
    };
  };
  ghost = {
    pname = "ghost";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "skanehira";
      repo = "ghost";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-PhHC1FOcUBS1ZK97hjJ7zJOsJql2JkSJHkZNZqRRAVc=";
    };
  };
  treesitter-ls = {
    pname = "treesitter-ls";
    version = "v0.0.2";
    src = fetchFromGitHub {
      owner = "atusy";
      repo = "treesitter-ls";
      rev = "v0.0.2";
      fetchSubmodules = false;
      sha256 = "sha256-9c7ttOX7SHvGbkSjPy0Yt9PB/8fOuu//ElO0fn+Snf0=";
    };
  };
}
