# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ghost = {
    pname = "ghost";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "skanehira";
      repo = "ghost";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-PhHC1FOcUBS1ZK97hjJ7zJOsJql2JkSJHkZNZqRRAVc=";
    };
  };
  treesitter-ls = {
    pname = "treesitter-ls";
    version = "v0.0.3";
    src = fetchFromGitHub {
      owner = "atusy";
      repo = "treesitter-ls";
      rev = "v0.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-t0v9avfGxsl6tFau19dqEDwdG9cP9YI4aTvh4RgFrmU=";
    };
  };
}
