# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ghost = {
    pname = "ghost";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "skanehira";
      repo = "ghost";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-PhHC1FOcUBS1ZK97hjJ7zJOsJql2JkSJHkZNZqRRAVc=";
    };
  };
}
